echo "filename:$0"
echo "first parameter:$1"
echo "secound_parameter:$2"
echo "quated value:$*"
echo "quated value:$@"
echo "total number of parameter:$#"
echo "exist status of last command executed:$?"
echo "position:$n"
echo "total number of arguments:$#"
echo "ARGUMENTS WHICH ARE DOUBLE QUATED AND IT TAKES ENTIRE LIST AS 1 ARGUMENT:$*"
echo "ALL THE ARGUMENTS ARE INDIVIDUALLY QUATED AND IT TAKES THE ENTIRE LISTS AND SEPERATE IT INTO SEPERATE ARGUMENT:$@"
echo "shell variable,process number of shell variable:$$"
echo "process number of last background command:$!"

